/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar usuario
         * @description Crea un nuevo usuario y devuelve un JWT válido
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credenciales del nuevo usuario */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.RegisterRequest"];
                };
            };
            responses: {
                /** @description Usuario creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.AuthResponse"];
                    };
                };
                /** @description Campos requeridos ausentes */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
                /** @description El email ya está registrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticar usuario
         * @description Verifica las credenciales y devuelve un JWT
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email y contraseña */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.LoginRequest"];
                };
            };
            responses: {
                /** @description Autenticación exitosa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.AuthResponse"];
                    };
                };
                /** @description Credenciales incorrectas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar workspaces
         * @description Devuelve los workspaces a los que pertenece el usuario autenticado
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.WorkspaceResponse"][];
                    };
                };
                /** @description Token JWT ausente o inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear workspace
         * @description Crea un nuevo workspace con el usuario autenticado como propietario
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Nombre del nuevo workspace */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.CreateWorkspaceRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.WorkspaceResponse"];
                    };
                };
                /** @description El nombre del workspace es requerido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
                /** @description Token JWT ausente o inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar proyectos
         * @description Devuelve los proyectos del workspace al que pertenece el usuario autenticado
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID del workspace */
                    workspaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.ProjectResponse"][];
                    };
                };
                /** @description workspaceId no es un número válido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
                /** @description Token JWT ausente o inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear proyecto
         * @description Crea un nuevo proyecto en el workspace especificado. La clave debe tener 1-10 caracteres alfanuméricos, empezando por letra
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID del workspace */
                    workspaceId: number;
                };
                cookie?: never;
            };
            /** @description Clave y nombre del proyecto */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.CreateProjectRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.dto.ProjectResponse"];
                    };
                };
                /** @description Parámetros inválidos o formato de clave incorrecto */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
                /** @description Token JWT ausente o inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
                /** @description La clave del proyecto ya existe en el workspace */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["me.dcueto.zentrackapp.api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorResponse */
        "me.dcueto.zentrackapp.api.ErrorResponse": {
            /** String */
            error: string;
        };
        /** RegisterRequest */
        "me.dcueto.zentrackapp.dto.RegisterRequest": {
            /** String */
            email: string;
            /** String */
            name: string;
            /** String */
            password: string;
        };
        /** AuthResponse */
        "me.dcueto.zentrackapp.dto.AuthResponse": {
            /** String */
            token: string;
        };
        /** LoginRequest */
        "me.dcueto.zentrackapp.dto.LoginRequest": {
            /** String */
            email: string;
            /** String */
            password: string;
        };
        /** WorkspaceResponse */
        "me.dcueto.zentrackapp.dto.WorkspaceResponse": {
            /** String */
            createdAt: string;
            /**
             * Long
             * Format: int64
             */
            id: number;
            /** String */
            name: string;
            /**
             * Long
             * Format: int64
             */
            ownerId: number;
        };
        /** CreateWorkspaceRequest */
        "me.dcueto.zentrackapp.dto.CreateWorkspaceRequest": {
            /** String */
            name: string;
        };
        /** ProjectResponse */
        "me.dcueto.zentrackapp.dto.ProjectResponse": {
            /** String */
            createdAt: string;
            /**
             * Long
             * Format: int64
             */
            id: number;
            /** String */
            name: string;
            /** String */
            projectKey: string;
            /**
             * Int
             * Format: int32
             */
            taskCounter: number;
            /**
             * Long
             * Format: int64
             */
            workspaceId: number;
        };
        /** CreateProjectRequest */
        "me.dcueto.zentrackapp.dto.CreateProjectRequest": {
            /** String */
            name: string;
            /** String */
            projectKey: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
